# geniushub-client - Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1


aliases:
  - &testbed_environment
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/working_directory

    environment:
      TEST_RESULTS: /tmp/workspace/test-results

  - &restore_cache
      restore_cache:
        keys:
          - v4-dependencies-{{ checksum "requirements.txt" }}

  - &save_cache
      save_cache:
        key: v4-dependencies-{{ checksum "requirements.txt" }}
        paths:
          - ./venv

  - &attach_workspace
      attach_workspace:
        at: /tmp/workspace

  - &persist_to_workspace
      persist_to_workspace:
        keys:
          - v4-dependencies-{{ checksum "requirements.txt" }}
        root: /tmp/workspace
        paths:
          - test-results

  - &store_artifacts
      store_artifacts:
        path: /tmp/workspace/test-results
        destination: test_results

  - &create_testbed
      - checkout
      - *restore_cache

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip  # setuptools wheel
            pip install -r requirements.txt

      - *save_cache

      - run: mkdir -p ${TEST_RESULTS}/issues
      - run: mkdir -p ${TEST_RESULTS}/devices
      - run: mkdir -p ${TEST_RESULTS}/zones

      - *persist_to_workspace


commands:
  get_v1_curl:
    description: "get v1 response via cURL"
    parameters:
      test_type:
        type: string
        default: "issues"
    steps:
      - checkout
      - *restore_cache
      - *attach_workspace
      - run:
          name: get v1 response via cURL
          no_output_timeout: 330
          command: |
            curl -X GET https://my.geniushub.co.uk/v1/<< parameters.test_type >> -H "authorization: Bearer ${HUB_TOKEN}" --connect-timeout 300 | \
              tee ${TEST_RESULTS}/<< parameters.test_type >>/curl.json
      - run:
          name: prepare cURL response
          no_output_timeout: 60
          command: |
            . venv/bin/activate
            cat ${TEST_RESULTS}/<< parameters.test_type >>/curl.json | python -c "import sys, json; print(json.load(sys.stdin))" | \
              tee ${TEST_RESULTS}/<< parameters.test_type >>/curl.json

      - *persist_to_workspace

  get_v1_app:
    description: "get v1 response via app"
    parameters:
      test_type:
        type: string
        default: "issues"
    steps:
      - checkout
      - *restore_cache
      - *attach_workspace
      - run:
          name: get v1 response via app
          no_output_timeout: 330
          command: |
            . venv/bin/activate
            python ghclient.py ${HUB_TOKEN} << parameters.test_type >> -v | \
              tee ${TEST_RESULTS}/<< parameters.test_type >>/v1.json
      - *persist_to_workspace

  get_v3_app:
    description: "get v3 response via app"
    parameters:
      test_type:
        type: string
        default: "issues"
    steps:
      - checkout
      - *restore_cache
      - *attach_workspace
      - run:
          name: get v3 response via app
          no_output_timeout: 120
          command: |
            . venv/bin/activate
            python ghclient.py ${HUB_ADDRESS} -u ${USERNAME} -p ${PASSWORD} << parameters.test_type >> -v | \
              tee ${TEST_RESULTS}/<< parameters.test_type >>/v3.json
      - *persist_to_workspace

  diff_files:
    description: "compare outputs"
    parameters:
      test_type:
        type: string
        default: "issues"
      api_ver:
        type: string
        default: "issues"
    steps:
      - *attach_workspace

      - run:
          name: diff files
          no_output_timeout: 60
          command: |
            diff -qs ${TEST_RESULTS}/<< parameters.test_type >>/curl.json ${TEST_RESULTS}/<< parameters.test_type >>/<< parameters.api_ver >>.json | \
              tee -a ${TEST_RESULTS}/<< parameters.test_type >>/results.txt

      - run:
          name: display differences
          no_output_timeout: 60
          when: on_fail
          command: |
            sudo apt -y install wdiff colordiff >/dev/null 2>&1
            wdiff ${TEST_RESULTS}/<< parameters.test_type >>/curl.json ${TEST_RESULTS}/<< parameters.test_type >>/<< parameters.api_ver >>.json | colordiff

      - *store_artifacts


jobs:
  make_testbed:
    <<: *testbed_environment
    steps: *create_testbed

  issues_curl:
    <<: *testbed_environment
    steps:
      - get_v1_curl:
          test_type: "issues"
  issues_v1:
    <<: *testbed_environment
    steps:
      - get_v1_app:
          test_type: "issues"
  issues_v3:
    <<: *testbed_environment
    steps:
      - get_v3_app:
          test_type: "issues"
  issues_diff_v1:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "issues"
          api_ver: "v1"
  issues_diff_v3:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "issues"
          api_ver: "v3"

  zones_curl:
    <<: *testbed_environment
    steps:
      - get_v1_curl:
          test_type: "zones"
  zones_v1:
    <<: *testbed_environment
    steps:
      - get_v1_app:
          test_type: "zones"
  zones_v3:
    <<: *testbed_environment
    steps:
      - get_v3_app:
          test_type: "zones"
  zones_diff_v1:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "zones"
          api_ver: "v1"
  zones_diff_v3:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "zones"
          api_ver: "v3"

  devices_curl:
    <<: *testbed_environment
    steps:
      - get_v1_curl:
          test_type: "devices"
  devices_v1:
    <<: *testbed_environment
    steps:
      - get_v1_app:
          test_type: "devices"
  devices_v3:
    <<: *testbed_environment
    steps:
      - get_v3_app:
          test_type: "devices"
  devices_diff_v1:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "devices"
          api_ver: "v1"
  devices_diff_v3:
    <<: *testbed_environment
    steps:
      - diff_files:
          test_type: "devices"
          api_ver: "v3"


workflows:
  version: 2.1
  test_issues:
    jobs:
      - make_testbed

      - issues_curl:
          requires:
            - make_testbed
      - issues_v1:
          requires:
            - make_testbed
      - issues_v3:
          requires:
            - make_testbed
      - issues_diff_v1:
          requires:
            - issues_curl
            - issues_v1
            - issues_v3
      - issues_diff_v3:
          requires:
            - issues_curl
            - issues_v1
            - issues_v3

  test_zones:
    jobs:
      - make_testbed

      - zones_curl:
          requires:
            - make_testbed
      - zones_v1:
          requires:
            - make_testbed
      - zones_v3:
          requires:
            - make_testbed
      - zones_diff_v1:
          requires:
            - zones_curl
            - zones_v1
            - zones_v3
      - zones_diff_v3:
          requires:
            - zones_curl
            - zones_v1
            - zones_v3

  test_devices:
    jobs:
      - make_testbed

      - devices_curl:
          requires:
            - make_testbed
      - devices_v1:
          requires:
            - make_testbed
      - devices_v3:
          requires:
            - make_testbed
      - devices_diff_v1:
          requires:
            - devices_curl
            - devices_v1
            - devices_v3
      - devices_diff_v3:
          requires:
            - devices_curl
            - devices_v1
            - devices_v3
